# -*- coding: utf-8 -*-
"""Sentiment Analysis using NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XSWRWyr239bzRLe9Fse9rPuM1OfmIQM

**Sentiment Analysis using NLP**

s**tep 1 - reading data & visualization** **bold text**

import libraries
"""

import pandas as pd
import nltk

"""##read datase


"""

df= pd.read_csv("/content/Tweets.csv",encoding="latin-1")

df.head(5)

df.shape

df = df[["airline_sentiment", "text"]]

df.head(5)

df.rename(columns={"airline_sentiment": "sentiment", "text": "tweet"}, inplace=True)

df.sample(5)

df.groupby("sentiment").describe()

df= df.drop_duplicates(keep='first')

df.groupby("sentiment").describe()

"""##data vizualization"""

df["length"] = df["tweet"].apply(len)

df.head(2)

"""##step 2- preprocessing"""

import nltk

import string

import re



from nltk.stem.porter import PorterStemmer



nltk.download('stopwords')

from nltk.corpus import stopwords



nltk.download('punkt')

ps = PorterStemmer()

df.head(5)

def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Tokenize the text
    text = nltk.word_tokenize(text)

    # Step 1: Keep only alphanumeric tokens
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    # Step 2: Remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()


    for i in text:
         if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    # Step 3: Apply stemming
    for i in text:
        y.append(ps.stem(i))

    # Return as a single cleaned string
    return " ".join(y)

import nltk
nltk.download('punkt_tab')
df['tweet cleaned'] = df['tweet'].apply(clean_text)

df.head(5)

"""##feature extraction step-3"""

from sklearn.feature_extraction.text import TfidfVectorizer

tf_vec= TfidfVectorizer(max_features=3000)
x=tf_vec.fit_transform(df['tweet cleaned']).toarray()

x.shape

y=df['sentiment'].values

"""##step4-learning"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(x_train,y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)

print(accuracy_score(y_test,y_pred))